server:
  port: 9097
  contextPath: /uaa

eureka:
  instance:
    prefer-ip-address: true
    non-secure-port: 9097
  client:
    egisterWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
security:
  #user:
  #name: root
  #password: password
 oauth2:
     resource:
 #      loadBalanced: true
       userInfoUri: http://localhost:9999/user
security.ignored: /resources/**

logging:
  level:
    org.springframework.security: TRACE
